Cia/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from Cia import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap



sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('captcha/', include('captcha.urls')),
    path('account/',include('allauth.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^robots\.txt', include('robots.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [  
                    path("__debug__/", include("debug_toolbar.urls")),
    ]

#  COMINGSOON
if settings.COMINGSOON:
    urlpatterns.insert(
            0, re_path(r"^", TemplateView.as_view(template_name="comingsoon.html"))
        )



handler400 = "Cia.error_views.error_400"     # bad request
handler403 = "Cia.error_views.error_403"     # permission denied
handler404 = "Cia.error_views.error_404"     # page not found
handler500 = "Cia.error_views.error_500"     # server error

blog/urls.py
from django.urls import path
from blog.views import *
from django.urls import path
from blog.feeds import LatestEntriesFeed


app_name = 'blog'


urlpatterns = [
    path('',blog_view,name='main'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('author/<str:author_user>',blog_view,name='author'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('search/',blog_search,name='search'),
    path("latest/feed/", LatestEntriesFeed()),
]

website/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.generic import TemplateView
from website.views import *
app_name = 'website'


urlpatterns = [
    path('',TemplateView.as_view(template_name='website/index.html'),name='index'),
    path('about',TemplateView.as_view(template_name='website/about.html'),name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),
]

website/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255,blank= True,null=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-created_date']
    def __str__(self):
        return f'{self.name} {self.id}'
class Newsletter(models.Model):
    email = models.EmailField()
    def __str__(self):
        return self.email

website/forms.py
from website.models import *
from django import forms
from captcha.fields import CaptchaField
class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Contact
        fields = '__all__'
class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

website/views.py
from django.shortcuts import render,redirect
from website.forms import *
import sweetify
# Create your views here.



def contact_view(request):
    """
    View function for the contact page.
    Allows users to submit a contact form.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The response object.
    """
    # If the request method is POST, create a new ContactForm instance
    # with the POST data and validate it.
    if request.method == 'POST':
        # Create a copy of the POST data and set the 'name' field to 'unknown'
        # if it is not provided.
        post = request.POST.copy()
        if 'name' not in post:
            post['name'] = 'unknown'
        
        form = ContactForm(post)
        
        # If the form is valid, save it and display a success message.
        # Redirect to the contact page.
        if form.is_valid():
            form.save()
            sweetify.success(request, 'Your message has been sent')
            return redirect('website:contact')
        # If the form is not valid, display an error message.
        # Redirect to the contact page.
        else:
            sweetify.error(request, 'Your message was not sent')
            return redirect('website:contact')
    
    # If the request method is not POST, create a new ContactForm instance.
    form = ContactForm()
    
    # Create a context dictionary containing the form.
    context = {'form': form}
    
    # Render the contact.html template with the context dictionary.
    return render(request, 'website/contact.html', context)




def newsletter_view(request):
    """
    View function for the newsletter sign-up page.
    Allows users to sign up for the newsletter.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The response object.
    """
    # If the request method is POST, create a new NewsletterForm instance
    # with the POST data and validate it.
    if request.method == 'POST':
        # Create a new NewsletterForm instance with the POST data
        form = NewsletterForm(request.POST)
        
        # If the form is valid, save it and display a success message.
        # Redirect to the home page.
        if form.is_valid():
            form.save()
            # Display a success message to the user
            sweetify.success(request, 'Thank you for subscribing to our newsletter')
            return redirect('/')
        # If the form is not valid, display an error message.
        # Redirect to the home page.
        else:
            sweetify.error(request, 'ERROR, Please try again')
            return redirect('/')
    
    # If the request method is not POST, create a new NewsletterForm instance.
    form = NewsletterForm()
    
    # Create a context dictionary containing the form.
    context = {'form': form}
    
    # Render the index.html template with the context dictionary.
    return render(request,'website/index.html',context)

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main class="main">
    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="container section-title" data-aos="fade-up">
              <h2>About Us</h2>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li>
              <a href="{% url 'website:index'%}">Home</a>
            </li>
            <li class="current">About</li>
          </ol>
        </div>
      </nav>
    </div>
    <!-- End Page Title -->

    <!-- About Section -->
    <section id="about" class="about section light-background">
      <div class="container" data-aos="fade-up" data-aos-delay="100">
        <div class="row align-items-xl-center gy-5">
          <div class="col-xl-5 content">
            <h3>About Us</h3>
            <p>Welcome to Cia Coffee Shop, located in the heart of Abadan. We serve a variety of coffee blends and delicious pastries crafted with care and quality.</p><p>Our team is dedicated to providing a comfortable and inviting atmosphere.Whether you're here for a quick coffee or a relaxed break,our goal is to ensure you enjoy your time with us.</p>
            <a href="#" class="read-more"><span>Read More</span><i class="bi bi-arrow-right"></i></a>
          </div>

          <div class="col-xl-7">
            <div class="row gy-4 icon-boxes">
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="200">
                <div class="icon-box">
                  <i class="bi bi-buildings"></i>
                  <h3>Eius provident</h3>
                  <p>Magni repellendus vel ullam hic officia accusantium ipsa dolor omnis dolor voluptatem</p>
                </div>
              </div> <!-- End Icon Box -->

              <div class="col-md-6" data-aos="fade-up" data-aos-delay="300">
                <div class="icon-box">
                  <i class="bi bi-clipboard-pulse"></i>
                  <h3>Rerum aperiam</h3>
                  <p>Autem saepe animi et aut aspernatur culpa facere. Rerum saepe rerum voluptates quia</p>
                </div>
              </div> <!-- End Icon Box -->

              <div class="col-md-6" data-aos="fade-up" data-aos-delay="400">
                <div class="icon-box">
                  <i class="bi bi-command"></i>
                  <h3>Veniam omnis</h3>
                  <p>Omnis perferendis molestias culpa sed. Recusandae quas possimus. Quod consequatur corrupti</p>
                </div>
              </div> <!-- End Icon Box -->

              <div class="col-md-6" data-aos="fade-up" data-aos-delay="500">
                <div class="icon-box">
                  <i class="bi bi-graph-up-arrow"></i>
                  <h3>Delares sapiente</h3>
                  <p>Sint et dolor voluptas minus possimus nostrum. Reiciendis commodi eligendi omnis quideme lorenda</p>
                </div>
              </div> <!-- End Icon Box -->
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- /About Section -->
  </main>
{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <main class="main">
    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <!-- Section Title -->
            <div class="container section-title" data-aos="fade-up">
              <h2>Contact</h2>
              <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
            </div>
            <!-- End Section Title -->
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li>
              <a href="{% url 'website:index' %}">Home</a>
            </li>
            <li class="current">Contact</li>
          </ol>
        </div>
      </nav>
    </div>
    <!-- End Page Title -->
    <!-- Contact Section -->
    <section id="contact" class="contact section">
      <div class="container" data-aos="fade-up" data-aos-delay="100">
        <div class="row gy-4">
          <div class="col-lg-6">
            <div class="row gy-4">
              <div class="col-md-6">
                <div class="info-item" data-aos="fade" data-aos-delay="200">
                  <i class="bi bi-geo-alt"></i>
                  <h3>Address</h3>
                  <p>Abadan</p>
                  <p>Brazil</p>
                </div>
              </div>
              <!-- End Info Item -->

              <div class="col-md-6">
                <div class="info-item" data-aos="fade" data-aos-delay="300">
                  <i class="bi bi-telephone"></i>
                  <h3>Call Us</h3>
                  <p>+98 916..</p>
                </div>
              </div>
              <!-- End Info Item -->

              <div class="col-md-6">
                <div class="info-item" data-aos="fade" data-aos-delay="400">
                  <i class="bi bi-envelope"></i>
                  <h3>Email Us</h3>
                  <p>mehdi.mousavi.rad1@gmail.com</p>
                </div>
              </div>
              <!-- End Info Item -->

              <div class="col-md-6">
                <div class="info-item" data-aos="fade" data-aos-delay="500">
                  <i class="bi bi-clock"></i>
                  <h3>Open Hours</h3>
                  <p>Monday - Friday</p>
                  <p>9:00AM - 05:00PM</p>
                </div>
              </div>
              <!-- End Info Item -->
            </div>
          </div>

          <div class="col-lg-6">
            <form action="{% url 'website:contact' %}" method="post" class="form-area" data-aos="fade-up" data-aos-delay="200">
              {% csrf_token %}
              <div class="row gy-4">
                <div class="col-md-6">
                  <input type="text" name="name" class="form-control" placeholder="Your Name" required=""  />
                </div>

                <div class="col-md-6">
                  <input type="email" class="form-control" name="email" placeholder="Your Email" required="" />
                </div>

                <div class="col-12">
                  <input type="text" class="form-control" name="subject" placeholder="Subject" required="" />
                </div>

                <div class="col-12">
                  <textarea class="form-control" name="message" rows="6" placeholder="Message" required=""></textarea>
                </div>
                <div class="col-12">
                  {{form.captcha}}
                </div>
                <div class="php-email-form">
                  <button class="form-control" type="submit">Send Message</button>
                </div>
              </div>
            </form>
          </div>
          <!-- End Contact Form -->
        </div>
      </div>
    </section>
    <!-- /Contact Section -->
  </main>
{% endblock %}

templates/website/latest_posts.html
{% load static %}
{%load humanize%}
<!-- Recent Posts Section -->
<section id="recent-posts" class="recent-posts section">
  <!-- Section Title -->
  <div class="container section-title" data-aos="fade-up">
    <h2>Recent Posts</h2>
    <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
  </div>
  <!-- End Section Title -->

  <div class="container">
    <div class="row gy-4">
      {% for post in posts %}
        <div class="col-xl-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
          <article>
            <div class="post-img">
              <img src="{{ post.image.url }}" alt="" class="img-fluid" />
            </div>
            {% for cat in post.category.all %}
              <a class="post-category">{{ cat.name }}</a>
              {% if not forloop.last %},{% endif %}
            {% endfor %}
            <h2 class="title"><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h2>

            <div class="d-flex align-items-center">
              <div class="post-meta">
                <p class="post-author">{{ post.author.get_full_name }}</p>
                <p class="post-date">
                  <time datetime="2022-01-01">{{ post.pub_date|naturalday }}</time>
                </p>
              </div>
            </div>
          </article>
        </div>
      {% endfor %}
      <!-- End post list item -->
    </div>
    <!-- End recent posts list -->
  </div>
</section>
<!-- /Recent Posts Section -->