Cia/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from Cia import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap



sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('captcha/', include('captcha.urls')),
    path('account/',include('allauth.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^robots\.txt', include('robots.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [  
                    path("__debug__/", include("debug_toolbar.urls")),
    ]

#  COMINGSOON
if settings.COMINGSOON:
    urlpatterns.insert(
            0, re_path(r"^", TemplateView.as_view(template_name="comingsoon.html"))
        )



handler400 = "Cia.error_views.error_400"     # bad request
handler403 = "Cia.error_views.error_403"     # permission denied
handler404 = "Cia.error_views.error_404"     # page not found
handler500 = "Cia.error_views.error_500"     # server error

blog/urls.py
from django.urls import path
from blog.views import *
from django.urls import path
from blog.feeds import LatestEntriesFeed


app_name = 'blog'


urlpatterns = [
    path('',blog_view,name='main'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('author/<str:author_user>',blog_view,name='author'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('search/',blog_search,name='search'),
    path("latest/feed/", LatestEntriesFeed()),
]

website/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.generic import TemplateView
from website.views import *
app_name = 'website'


urlpatterns = [
    path('',TemplateView.as_view(template_name='website/index.html'),name='index'),
    path('about',TemplateView.as_view(template_name='website/about.html'),name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.



class Tags(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
    
    
class Categories(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
    
    
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()
    author = models.ForeignKey(User,on_delete=models.SET_NULL, null = True)
    image = models.ImageField(upload_to='blog/',default='blog/blog-img2.png')
    profile = models.ImageField(upload_to='blog/profile/',default='blog/profile/profile.jpg')
    tags = TaggableManager()
    status_type = models.TextChoices("status_type",'published unpublished')
    status = models.CharField(blank=True, choices=status_type.choices, max_length=15)
    category = models.ManyToManyField(Categories)
    login_required = models.BooleanField(default=False)
    counted_views = models.IntegerField(default = 0)
    created_date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(null=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-pub_date']
    def __str__(self):
        return f'{self.title} {self.id}'
    
    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pid": self.id})
    
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    subject = models.CharField(max_length=150)
    name = models.CharField(max_length=150)
    email = models.EmailField()
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    approved = models.BooleanField(default=False)
    class Meta:
        ordering = ['-created_date']
    def __str__(self):
        return f'{self.name} {self.email}'

blog/forms.py
from django.forms import ModelForm
from blog.models import *



class CommentForm(ModelForm):
    
    class Meta:
        
        model = Comment

        fields = ['post','email','name','subject','content']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import *
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.utils import timezone
from blog.forms import CommentForm
import sweetify
# Create your views here.


def blog_view(request, **kwargs):
    """
    View function for rendering the blog page.
    It retrieves posts based on the provided kwargs and paginates them.
    
    Args:
        request (HttpRequest): The HTTP request object.
        **kwargs: Additional keyword arguments for filtering the posts.
        
    Returns:
        HttpResponse: The rendered blog page with the posts.
    """
    
    # Retrieve published posts
    posts = Post.objects.filter(
        pub_date__lte=timezone.now(),
        status='published'
    ).order_by('-pub_date')
    
    # Filter posts based on the provided kwargs
    if kwargs.get('author_user'):
        posts = posts.filter(author__username=kwargs['author_user'])
    if kwargs.get('cat_name'):
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('tag_name'):
        posts = posts.filter(tags__name=kwargs['tag_name'])
    
    # Paginate the posts
    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page')
    
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(1)

    # Create the context dictionary
    context = {'posts': posts}
    
    # Render the blog page with the posts
    return render(request, 'blog/blog.html', context)


def blog_single(request, pid):
    """
    This function displays a single blog post and handles form submission for comments.
    
    Args:
        request: The HTTP request object.
        pid: The primary key of the blog post.
        
    Returns:
        Rendered HTML page displaying the single blog post.
    """
    
    # Get the specified blog post
    post = get_object_or_404(Post, pk=pid, status='published', pub_date__lte=timezone.now())
    
    # Check if the post requires login
    if post.login_required and not request.user.is_authenticated:
        # Require login for specific posts
        return redirect('account_login')  # Redirect to login page
    
    # Get the next and previous posts
    next_post = Post.objects.filter(pub_date__gt=post.pub_date, status='published').order_by('pub_date').first()
    prev_post = Post.objects.filter(pub_date__lt=post.pub_date, status='published').order_by('-pub_date').first()
    
    # Increment the number of views for the post
    post.counted_views += 1
    post.save()
    
    if request.method == 'POST':
        # Handle form submission for comments
        form = request.POST.copy()
        form['post'] = post.id
        form = CommentForm(form)
        
        if form.is_valid():
            # Save the comment
            form.save()
            sweetify.success(request, 'Your comment submitted successfully')
        else:
            sweetify.error(request, 'Your comment didn\'t submit')
    
    # Display form for comments
    form = CommentForm()
    comments = Comment.objects.filter(post__id=pid, approved=True)
    
    # Render the HTML page
    context = {
        'post': post,
        'comments': comments,
        'form': form,
        'next_post': next_post,
        'prev_post': prev_post
    }
    
    return render(request, 'blog/blog-details.html', context)


def blog_category(request, cat_name):
    """
    This function displays a list of blog posts based on the provided category name.

    Args:
        request: The HTTP request object.
        cat_name: The name of the category.

    Returns:
        Rendered HTML page displaying the filtered blog posts.
    """
    # Filter blog posts based on status and category name
    posts = Post.objects.filter(status='published')
    posts = posts.filter(category__name=cat_name)
    
    # Create context dictionary with the filtered posts
    context = {
        'posts': posts,
    }
    
    # Render the HTML page with the context
    return render(request,'blog/blog.html', context)


def blog_search(request):
    """
    This function displays a list of blog posts based on the search query.

    Args:
        request: The HTTP request object.

    Returns:
        Rendered HTML page displaying the filtered blog posts.
    """
    # Retrieve all published posts
    posts = Post.objects.filter(
        pub_date__lte=timezone.now(),
        status='published'
    ).order_by('-pub_date')

    # If the request method is GET and a search query is provided, filter the posts
    if request.method == 'GET':
        # Retrieve the search query from the request
        search_query = request.GET.get('s')
        if search_query:
            posts = posts.filter(content__contains=search_query)

    # Create a context dictionary with the filtered posts
    context = {'posts': posts}

    # Render the HTML page with the context
    return render(request, 'blog/blog.html', context)

templates/blog/blog-details.html
{% extends "base.html" %}
{% load blog_tags %}
{% load humanize %}
{% load static %}
<!DOCTYPE html>
  {% block content %}
  <main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Blog Details</h1>
              <p class="mb-0"></p>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li><a href="{% url 'website:index' %}">Home</a></li>
            <li><a href="{% url 'blog:main' %}">Blog</a></li>
            <li class="current">Blog Details</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Page Title -->

    <div class="container">
      <div class="row">

        <div class="col-lg-8">

          <!-- Blog Details Section -->
          <section id="blog-details" class="blog-details section">
            <div class="container">

              <article class="article">

                <div class="post-img">
                  <img src="assets/img/blog/blog-1.jpg" alt="" class="img-fluid">
                </div>

                <h2 class="title">{{post.title}}</h2>

                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url "blog:author" author_user=post.author %}">{{post.author}}</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a ><time datetime="2020-01-01">{{post.pub_date|naturalday}}</time></a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a >{{comments|length}}</a></li>
                  </ul>
                </div><!-- End meta top -->

                <div class="content">
                  {{post.content|safe}}
                </div><!-- End post content -->

                <div class="meta-bottom">
                  <i class="bi bi-folder"></i>
                  <ul class="cats">
                    {% for cat in post.category.all %}
                      <li><a href="{% url 'blog:category' cat_name=cat.name%}">{{cat.name}}</a>{% if not forloop.last%},{% endif %}</li>
                    {% endfor %}
                  </ul>

                  <i class="bi bi-tags"></i>
                  <ul class="tags">
                  {% for tag in post.tags.all %}
                    <li><a href="{% url 'blog:tag' tag_name=tag.name%}">{{tag.name}}</a>{% if not forloop.last%},{% endif %}</li>
                  {% endfor %}
                  </ul>
                </div><!-- End meta bottom -->

              </article>

            </div>
          </section><!-- /Blog Details Section -->

          <!-- Blog Author Section -->
          <section id="blog-author" class="blog-author section">

            <div class="container">
              <div class="author-container d-flex align-items-center">
                <img src="assets/img/blog/blog-author.jpg" class="rounded-circle flex-shrink-0" alt="">
                <div>
                  <h4>{{post.author}}</h4>
                  <div class="social-links">
                    <a href="https://x.com/#"><i class="bi bi-twitter-x"></i></a>
                    <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                    <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                  </div>
                  <p>
                    Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                  </p>
                </div>
              </div>
            </div>

          </section><!-- /Blog Author Section -->
          <div class="next-prev">
            {% if prev_post %}
            <a href="{{prev_post.id}}" class="prev">prev post</a>
            {% endif %}
            {% if next_post %}
            <a href="{{next_post.id}}" class="next">Next post</a>
            {% endif %}
          </div>
          <!-- Blog Comments Section -->
          <section id="blog-comments" class="blog-comments section">

            <div class="container">

              <h4 class="comments-count">{{comments|length}} Comments</h4>
              {% for comment in comments%}
                <div id="comment-1" class="comment">
                  <div class="d-flex">
                    <div class="comment-img"><img src="{{post.profile.url}}" alt=""></div>
                    <div>
                      <h5><a href="">{{comment.name}}</a> <a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a></h5>
                      <time datetime="2020-01-01">{{comment.created_date|naturaltime}}</time>
                      {{comment.content}}
                    </div>
                  </div>
                </div><!-- End comment #1 -->
              {% endfor %}
            </div>

          </section><!-- /Blog Comments Section -->

          <!-- Comment Form Section -->
          <section id="comment-form" class="comment-form section">
            <div class="container">

              <form method="post">
                {% csrf_token %}
                <h4>Post Comment</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                {% if request.user.is_authenticated%}
                  <input type="hidden" class="form-control" name="name" value="{{user.first_name}}"/>
                  <input type="hidden" class="form-control" name="email" value="{{user.email}}"/>
                {% else %}
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*">
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="email" class="form-control" placeholder="Your Email*">
                    </div>
                  </div>
                {% endif %}
                <div class="row">
                  <div class="col form-group">
                    <input name="subject" type="text" class="form-control" placeholder="Subject">
                  </div>
                </div>
                <div class="row">
                  <div class="col form-group">
                    <textarea name="content" class="form-control" placeholder="Your Comment*"></textarea>
                  </div>
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Post Comment</button>
                </div>

              </form>

            </div>
          </section><!-- /Comment Form Section -->

        </div>

        <div class="col-lg-4 sidebar">

          <div class="widgets-container">
            {% include 'blog/blog_search.html' %}

            {% postcategories %}

            {% blog_latest %}

            {% blog_tags %}
          </div>
      </div>
    </div>

  </main>
  {% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
<!DOCTYPE html>
{% block content %}
  <main class="main">
    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="heading">
        <div class="container">
          <div class="row d-flex justify-content-center text-center">
            <div class="col-lg-8">
              <h1>Blog</h1>
              <p class="mb-0">Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
            </div>
          </div>
        </div>
      </div>
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li>
              <a href="{% url 'website:index' %}">Home</a>
            </li>
            <li class="current">Blog</li>
          </ol>
        </div>
      </nav>
    </div>
    <!-- End Page Title -->

    <!-- Blog Posts Section -->
    <div class="row" style="margin-left: 0px;">
      <section id="blog-posts" class="col-lg-8 blog-posts section">

        <div class="container">
          <div class="row gy-4">

            {% for post in posts %}

              <div class="col-lg-4">
                <article>
                  
                  <div class="post-img">
                    <img style="height:200px;max-width:280px;width: expression(this.width > 500 ? 500: true);" src="{{ post.image.url }}" alt="" class="img-fluid" />
                  </div>
                  {% for cat in post.category.all %}
                    <a href="{% url 'blog:category' cat_name=cat.name %}" class="post-category">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
                  {% endfor %}
                  <h2 class="title">
                    <a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a>
                  </h2>
                  <p >{{ post.content|truncatewords_html:10|safe }}</p>
                  <div class="d-flex align-items-center">
                    <img src="{{post.profile.url}}" alt="" class="img-fluid post-author-img flex-shrink-0" />
                    <div class="post-meta">
                      <a href="{% url 'blog:author' author_user=post.author %}" class="post-author">{{post.author}}</a>
                      <p class="post-date">
                        <time datetime="2022-01-01">{{post.pub_date|naturalday}}</time>
                      </p>                 
                  </div>
                  </div>
                  <div class="header-card">
                    <p class="view"><i class="bi bi-eye"> {{post.counted_views}}</i></p> <!-- view post -->
                    <a href="{% url 'blog:single' pid=post.id %}" class="view-more">view more...</a> <!-- view more -->

                  </div>

                </article>
              </div>
              <!-- End post list item -->
            {% endfor %}
          </div>
        </div>
      </section>
      <!-- /Blog Posts Section -->
      <div class="col-lg-4 sidebar" style="width: 415px;">
        <div class="widgets-container">
          {% include 'blog/blog_search.html' %}

          {% postcategories %}

          {% blog_latest %}


          {% blog_tags %}
        </div>
      </div>
    </div>
    <!-- Blog Pagination Section -->
    <section id="blog-pagination" class="blog-pagination section">
      <div class="container">
        <div class="d-flex justify-content-center">
          <ul>
            {% if posts.has_previous %}
              <li>
                <a href="?page={{ posts.previous_page_number }}"><i class="bi bi-chevron-left"></i></a>
              </li>
            {% endif %}
            {% for page in posts.paginator.page_range %}
              {% if posts.number == page %}
                <li>
                  <a href="?page={{ page }}" class="active">{{ page }}</a>
                </li>
              {% else %}
                <li>
                  <a href="?page={{ page }}">{{ page }}</a>
                </li>
              {% endif %}
            {% endfor %}
            {% if post.has_next %}
              <li>
                <a href="?page={{ page }}"><i class="bi bi-chevron-right"></i></a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </section>
    <!-- /Blog Pagination Section -->
  </main>
{% endblock %}

templates/blog/blog_cat.html
{% load static %}
<!-- Categories Widget -->
<div class="categories-widget widget-item">
  <h3 class="widget-title">Categories:</h3>
  <ul class="mt-3">
    {% for name, count in categories.items %}
      <li>
        <a href="{% url 'blog:category' cat_name=name %}">{{ name }} <span>({{ count }})</span></a>
      </li>
    {% endfor %}
  </ul>
</div>
<!-- /Categories Widget -->

templates/blog/blog_recent.html
{% load static %}
{% load humanize %}
<!-- recent Posts Widget -->
<div class="recent-posts-widget widget-item">
  <h3 class="widget-title">Recent Posts</h3>
  {% for post in posts %}
    <div class="post-item">
      <img src="{{ post.image.url }}" alt="" class="flex-shrink-0" />
      <div>
        <h4><a href="{% url 'blog:single' pid=post.id %}">{{ post.title }}</a></h4>
        <time datetime="2020-01-01">{{ post.pub_date|naturaltime }}</time>
      </div>
    </div>
  {% endfor %}

  <!-- End recent post item -->
</div>

templates/blog/blog_search.html
{% load static %}
<!-- Search Widget -->
<div class="search-widget widget-item">
  <h3 class="widget-title">Search</h3>
  <form action="{% url 'blog:search' %}" method="GET">
    <input type="text" name="s" />
    <button type="submit" title="Search"><i class="bi bi-search"></i></button>
  </form>
</div>
<!-- /Search Widget -->

templates/blog/blog_tags.html
{% load static %}
<!-- Tags Widget -->
<div class="tags-widget widget-item">
  <h3 class="widget-title">Tags:</h3>
  <ul>
    {% for tag in tags %}
      <li>
        <a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a>
      </li>
    {% endfor %}
  </ul>
</div>
<!-- /Tags Widget -->