Cia/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from Cia import settings
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap



sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('captcha/', include('captcha.urls')),
    path('account/',include('allauth.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('blog/', include('blog.urls')),
    re_path(r'^robots\.txt', include('robots.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [  
                    path("__debug__/", include("debug_toolbar.urls")),
    ]

#  COMINGSOON
if settings.COMINGSOON:
    urlpatterns.insert(
            0, re_path(r"^", TemplateView.as_view(template_name="comingsoon.html"))
        )



handler400 = "Cia.error_views.error_400"     # bad request
handler403 = "Cia.error_views.error_403"     # permission denied
handler404 = "Cia.error_views.error_404"     # page not found
handler500 = "Cia.error_views.error_500"     # server error

blog/urls.py
from django.urls import path
from blog.views import *
from django.urls import path
from blog.feeds import LatestEntriesFeed


app_name = 'blog'


urlpatterns = [
    path('',blog_view,name='main'),
    path('<int:pid>',blog_single,name='single'),
    path('category/<str:cat_name>',blog_view,name='category'),
    path('author/<str:author_user>',blog_view,name='author'),
    path('tag/<str:tag_name>',blog_view,name='tag'),
    path('search/',blog_search,name='search'),
    path("latest/feed/", LatestEntriesFeed()),
]

website/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.generic import TemplateView
from website.views import *
app_name = 'website'


urlpatterns = [
    path('',TemplateView.as_view(template_name='website/index.html'),name='index'),
    path('about',TemplateView.as_view(template_name='website/about.html'),name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter_view,name='newsletter'),
]

templates/base.html
{% load static %}
{% load account %}
{% user_display user as user_display %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Cia Cafe</title>
    <meta content="Enjoy freshly brewed coffee, artisanal pastries, and cozy workspaces with free Wi-Fi at Cia Cafe in Abadan. Perfect spot for friends and individuals to unwind." name="description" />
    <meta content="Cia,Cafe,Coffee,Shop" name="keywords" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://themehdimsv.ir/" />
    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon" />
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon" />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />

    <!-- Vendor CSS Files -->
    {% compress css %}
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    {% endcompress %}
    {% compress css %}
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet" />
    {% endcompress %}
    {% compress css %}
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    {% endcompress %}
    {% compress css %}
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet" />
    {% endcompress %}
    {% compress css %}
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet" />
    {% endcompress %}
    <!-- Main CSS File -->
    {% compress css %}
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" />
    {% endcompress %}
    <!--      =======================================================
  * Template Name: Append
  * Template URL: https://bootstrapmade.com/append-bootstrap-website-template/
  * Updated: Jun 29 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ========================================================      -->
  </head>
  <body class="index-page">
    <header id="header" class="header d-flex align-items-center fixed-top">
      <div class="container-fluid position-relative d-flex align-items-center justify-content-between">
        <a href="{% url 'website:index' %}" class="logo d-flex align-items-center me-auto me-xl-0">
          <!-- Uncomment the line below if you also wish to use an image logo -->
          <!-- <img src="{% static 'assets/img/logo.png' %}" alt=""> -->
          <h1 class="sitename">Cia Cafe</h1><span>.</span>
        </a>
        <div class="col-lg-6 col-sm-6 col-6 header-top-left">
          <ul>
            {% if request.user.is_authenticated %}
              <li>
                <a href="{% url 'account_login' %}?next={{ request.get_full_path|urlencode }}">Logged In As {{ user_display }}</a>
              </li>
              <li>
                <a href="{% url 'account_logout' %}">Logout</a>
              </li>
            {% endif %}
            {% if not request.user.is_authenticated %}
              <li>
                <a href="{% url 'account_login' %}?next={{ request.get_full_path|urlencode }}">login</a>
              </li>
              <li>
                <a href="{% url 'account_signup' %}">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </div>
        <nav id="navmenu" class="navmenu">
          <ul>
            <li>
              <a href="{% url 'website:index' %}" class="active">Home</a>
            </li>
            <li>
              <a href="{% url 'website:about' %}">About</a>
            </li>
            <li>
              <a href="{% url 'blog:main' %}">Blog</a>
            </li>
            <li>
              <a href="{% url 'website:contact' %}">Contact</a>
            </li>
          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>
      </div>
    </header>

    {% block content %}

    {% endblock %}
    <footer id="footer" class="footer position-relative light-background">
      <div class="container footer-top">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-about">
            <a href="{% url 'website:index' %}" class="logo d-flex align-items-center"><span class="sitename">Cia Cafe</span></a>
            <p>Enjoy a perfect cup made from high-quality beans, brewed fresh for every order.</p>
            <div class="social-links d-flex mt-4">
              <a href=""><i class="bi bi-twitter-x"></i></a>
              <a href=""><i class="bi bi-facebook"></i></a>
              <a href=""><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li>
                <a href="{% url 'website:index' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'website:about' %}">About us</a>
              </li>
              <li>
                <a href="{% url 'website:contact' %}">Contact</a>
              </li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>ABADAN</p>
            <p>Brazil</p>
            <p class="mt-4">
              <strong>Phone:</strong> <span>+98 916...</span>
            </p>
            <p>
              <strong>Email:</strong> <span>mehdi.mousavi.rad1@gmail.com</span>
            </p>
          </div>
        </div>
      </div>

      <div class="container copyright text-center mt-4">
        <p>
          © <span>Copyright</span> <strong class="sitename">Cia</strong> <span>All Rights Reserved</span>
        </p>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you've purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    {% compress js %}
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    {% endcompress %}

    <!-- Main JS File -->
    {% compress js %}
    <script src="{% static 'assets/js/main.js' %}"></script>
    {% endcompress %}
  </body>
</html>
{% include 'messages.html' %}

templates/comingsoon.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Coming Soon 5</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- =============================================================================================== -->
    <link rel="icon" type="image/png" href="{% static 'assets/images/icons/favicon.ico' %}" />
    <!-- =============================================================================================== -->
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" />
    <!-- =============================================================================================== -->
    {% endcompress %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/font-awesome-4.7.0/css/font-awesome.min.css' %}" />
    <!-- =============================================================================================== -->
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/animate/animate.css' %}" />
    <!-- =============================================================================================== -->
    {% endcompress %}
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/select2/select2.min.css' %}" />
    <!-- =============================================================================================== -->
    {% endcompress %}
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/util.css' %}" />
    {% endcompress %}
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/comingsoon_main.css' %}" />
    <!-- =============================================================================================== -->
  </head>
  <body>
    <div class="bg-g1 size1 flex-w flex-col-c-sb p-l-15 p-r-15 p-b-30">
      <div class="flex-col-c w-full p-t-50 p-b-80">
        <h3 class="l1-txt1 txt-center p-b-10">Coming Soon</h3>

        <p class="txt-center l1-txt2 p-b-43 wsize2">Our website is under construction!</p>
      </div>
    </div>

    <!-- =============================================================================================== -->
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- =============================================================================================== -->
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/bootstrap/js/popper.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- =============================================================================================== -->
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/select2/select2.min.js' %}"></script>
    <!-- =============================================================================================== -->
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/countdowntime/moment.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/countdowntime/moment-timezone.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/countdowntime/moment-timezone-with-data.min.js' %}"></script>
    {% endcompress %}
    {% compress js %}
    <script src="{% static 'assets/vendor/countdowntime/countdowntime.js' %}"></script>
    {% endcompress %}
    <script>
      $('.cd100').countdown100({
        // Set Endtime here
        // Endtime must be > current time
        endtimeYear: 0,
        endtimeMonth: 0,
        endtimeDate: 35,
        endtimeHours: 18,
        endtimeMinutes: 0,
        endtimeSeconds: 0,
        timeZone: ''
        // ex:  timeZone: "America/New_York", can be empty
        // go to " http://momentjs.com/timezone/ " to get timezone
      })
    </script>
    <!-- =============================================================================================== -->
    <script src="{% static 'assets/vendor/tilt/tilt.jquery.min.js' %}"></script>
    <script>
      $('.js-tilt').tilt({
        scale: 1.1
      })
    </script>
    <!-- =============================================================================================== -->
    {% compress js %}
    <script src="{% static 'assets/js/comingsoon_main.js' %}"></script>
    {% endcompress %}
  </body>
</html>

templates/messages.html
{% load static %}

 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
                                      
        {% endblock title %}
    </title>
</head>
<body>
  
  {% block body %}
   
  {% endblock body %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.6.5/sweetalert2.all.min.js"></script>
  

</body>
</html>


{% load sweetify %}
{% sweetify %}